"""Add trading_style to Signal model

Revision ID: 53646699d73f
Revises: 0d94949484d7
Create Date: 2025-06-11 06:17:18.663582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53646699d73f'
down_revision: Union[str, None] = '0d94949484d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('signals', sa.Column('trading_style', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'trading_style')
    op.drop_column('signals', 'label')
    # ### end Alembic commands ###
