"""Add setup_conditions to signals

Revision ID: 932b7750a282
Revises: fc30a0fea708
Create Date: 2025-06-16 05:50:39.280614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932b7750a282'
down_revision: Union[str, None] = 'fc30a0fea708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('setup_conditions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'setup_conditions')
    # ### end Alembic commands ###
